jms_security_extra:
    secure_all_services: false
    expressions: true

security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        in_memory:
            memory:
                users:
                    olc: { password: ue8HFQgT0Z0vZtt9, roles: [ 'ROLE_USER' ] }
                    #wgeraedts: { password: test, roles: [ 'ROLE_ADMIN' ] }

    firewalls:
       main:
            pattern: ^/
            anonymous: ~
            http_basic:
                realm: "OLC Cloaca"

    access_control:
        - { path: ^/, roles: ROLE_USER }
